url: ""
baseurl: ""
title: "hfr4"

defaults:
  - scope:
      path: "assets/cards"
    values:
      is_card: true

webrick:
  headers:
    Cross-Origin-Opener-Policy: same-origin
    Cross-Origin-Embedder-Policy: require-corp